name: test_application
on: [pull_request, push]
jobs:
  jest:
    runs-on: ubuntu-latest
    using: 'node16'
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run test